%f

diff --git a/wayland/.config/hypr/grimblast b/wayland/.config/hypr/grimblast
--- a/wayland/.config/hypr/grimblast
+++ b/wayland/.config/hypr/grimblast
@@ -3,10 +3,11 @@
 ## Requirements:
 ##  - `grim`: screenshot utility for wayland
 ##  - `slurp`: to select an area
-##  - `hyprctl`: to read properties of current window
-##  - `wl-copy`: clipboard utility
+##  - `hyprctl`: to read properties of current window (provided by Hyprland)
+##  - `hyprpicker`: to freeze the screen when selecting area
+##  - `wl-copy`: clipboard utility (provided by wl-clipboard)
 ##  - `jq`: json utility to parse hyprctl output
-##  - `notify-send`: to show notifications
+##  - `notify-send`: to show notifications (provided by libnotify)
 ## Those are needed to be installed, if unsure, run `grimblast check`
 ##
 ## See `man 1 grimblast` or `grimblast usage` for further details.
@@ -41,6 +42,7 @@ env_editor_confirm() {
 NOTIFY=no
 CURSOR=
 FREEZE=
+WAIT=no
 SCALE=
 HYPRPICKER_PID=-1
 
@@ -59,6 +61,15 @@ while [ $# -gt 0 ]; do
   -f | --freeze)
     FREEZE=yes
     shift # past argument
+    ;;
+  -w | --wait)
+    shift
+    WAIT=$1
+    if echo "$WAIT" | grep "[^0-9]" -q; then
+      echo "Invalid value for wait '$WAIT'" >&2
+      exit 3
+    fi
+    shift
     ;;
   -s | --scale)
     shift # past argument
@@ -83,7 +94,7 @@ FILE_EDITOR=${3:-$(tmp_editor_directory)/$(date -Ins).png}
 
 if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "edit" ] && [ "$ACTION" != "copysave" ] && [ "$ACTION" != "check" ]; then
   echo "Usage:"
-  echo "  grimblast [--notify] [--cursor] [--freeze] [--scale <scale>] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
+  echo "  grimblast [--notify] [--cursor] [--freeze] [--wait N] [--scale <scale>] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
   echo "  grimblast check"
   echo "  grimblast usage"
   echo ""
@@ -123,6 +134,12 @@ notifyError() {
   fi
 }
 
+resetFade() {
+  if [[ -n $FADELAYERS ]]; then
+    hyprctl keyword animation "$FADELAYERS" >/dev/null
+  fi
+}
+
 killHyprpicker() {
   if [ ! $HYPRPICKER_PID -eq -1 ]; then
     kill $HYPRPICKER_PID
@@ -156,6 +173,13 @@ takeScreenshot() {
     grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" || die "Unable to invoke grim"
   else
     grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE" || die "Unable to invoke grim"
+    resetFade
+  fi
+}
+
+wait() {
+  if [ "$WAIT" != "no" ]; then
+    sleep "$WAIT"
   fi
 }
 
@@ -170,14 +194,17 @@ if [ "$ACTION" = "check" ]; then
   check notify-send
   exit
 elif [ "$SUBJECT" = "active" ]; then
+  wait
   FOCUSED=$(hyprctl activewindow -j)
   GEOM=$(echo "$FOCUSED" | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')
   APP_ID=$(echo "$FOCUSED" | jq -r '.class')
   WHAT="$APP_ID window"
 elif [ "$SUBJECT" = "screen" ]; then
+  wait
   GEOM=""
   WHAT="Screen"
 elif [ "$SUBJECT" = "output" ]; then
+  wait
   GEOM=""
   OUTPUT=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true)' | jq -r '.name')
   WHAT="$OUTPUT"
@@ -190,26 +217,22 @@ elif [ "$SUBJECT" = "area" ]; then
 
   # get fade & fadeOut animation and unset it
   # this removes the black border seen around screenshots
-  FADE="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fade") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", .bezier')"
-  FADEOUT="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fadeOut") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", .bezier')"
-  hyprctl keyword animation 'fade,0,1,default' >/dev/null
-  hyprctl keyword animation 'fadeOut,0,1,default' >/dev/null
+  FADELAYERS="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fadeLayers") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", .bezier')"
+  hyprctl keyword animation 'fadeLayers,0,1,default' >/dev/null
 
   WORKSPACES="$(hyprctl monitors -j | jq -r 'map(.activeWorkspace.id)')"
   WINDOWS="$(hyprctl clients -j | jq -r --argjson workspaces "$WORKSPACES" 'map(select([.workspace.id] | inside($workspaces)))')"
-  GEOM=$(echo "$WINDOWS" | jq -r '.[] | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | slurp)
-
-
-  # reset fade
-  hyprctl keyword animation "$FADE" >/dev/null
-  hyprctl keyword animation "$FADEOUT" >/dev/null
+  # shellcheck disable=2086 # if we don't split, spaces mess up slurp
+  GEOM=$(echo "$WINDOWS" | jq -r '.[] | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | slurp $SLURP_ARGS)
 
   # Check if user exited slurp without selecting the area
   if [ -z "$GEOM" ]; then
     killHyprpicker
+    resetFade
     exit 1
   fi
   WHAT="Area"
+  wait
 elif [ "$SUBJECT" = "window" ]; then
   die "Subject 'window' is now included in 'area'"
 else
